'''
Author: Ful Chou
Date: 2021-01-15 15:47:28
LastEditors: Ful Chou
LastEditTime: 2021-01-15 16:51:19
FilePath: /spider/Users/vincent/Development/SpiderOrTool/byb_new.py
Description: What this document does
'''
# Generated by Selenium IDE
from unittest.main import main
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import unittest

'''
 手动 填写一个同学的半月报之后 就可以使用此脚本 自动填写 接下来 N 个同学的信息：
 环境信息： python 3.6.3
 quick start：
 pip install pytest
 pip install selenium
 
 python new_byb.py
'''

username = ''
password = ''
n = 30 # 想要填写的同学数

class TestAddone(unittest.TestCase):
  def setup_method(self, method):
    self.driver = webdriver.Chrome('./chromedriver') # download in google
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addone(self):
    for _ in range(n):  
      self.setup_method('')
      self.driver.get("http://ca.its.csu.edu.cn/home/login/69")
      self.driver.set_window_size(1440, 875)
      self.driver.find_element(By.ID, "userName").click()
      self.driver.find_element(By.ID, "userName").send_keys(username)
      self.driver.find_element(By.ID, "passWord").send_keys(password)
      self.driver.find_element(By.ID, "login-btn").click()
      self.driver.switch_to.frame(1)
      self.driver.find_element(By.LINK_TEXT, "详情 >>").click()
      self.driver.find_element(By.LINK_TEXT, "修改").click()
      self.driver.find_element(By.LINK_TEXT, "评分").click()
      self.driver.switch_to.frame(0)
      time.sleep(1) #默认等待1秒
      self.driver.find_element(By.NAME, "xyqk").click()
      time.sleep(0.5) #默认等待0.5秒
      self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) input:nth-child(4)").click()
      self.driver.find_element(By.NAME, "rjgx").click()
      self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) input:nth-child(4)").click()
      self.driver.find_element(By.NAME, "xldj").click()
      self.driver.find_element(By.ID, "tj").click()
      dropdown = self.driver.find_element(By.ID, "tj")
      dropdown.find_element(By.XPATH, "//option[. = '观察']").click()
      self.driver.find_element(By.ID, "btnSubmit").click()
      self.teardown_method('')
    
if __name__ == "__main__":
  unittest.main()
